### ISSUE TITLE
usage of cfr_net_train.py

### ISSUE THREAD

**Issue by fxiao7** [clinicalml/cfrnet#1]
Hi, I'd like to use cfrnet code to run counterfactual analysis. Shall we use cfr_net_train.py to train a model? If so, then what's the usage to call this script? I tried the default setting, but it failed with errors to find files. Thanks for your answer.

**Comment by oddrose** [comment]
Hi. I think the easiest way to run the code is to run the example example_ihdp.sh and modify it for your purposes. This is described in the readme file. Let me know if you run into trouble.

**Comment by fxiao7** [comment]
Thanks a lot! Got it run now. 

PS: some methods/modules need to be fixed for it to run in Windows since tensorflow requires python 3.5.X while there are some methods/modules only supported in python 2
