### ISSUE TITLE
'res' in cfr_net.py line 149 is not defined

### ISSUE THREAD

**Issue by dachylong** [clinicalml/cfrnet#6]
'res' in cfr_net.py line 149 is not defined.

It should be
res = tf.abs(y - y_)

or just use 'risk' equivalently.

**Comment by oddrose** [comment]
Thanks for pointing this out!
I will address this on July 9 the earliest, but I appreciate this a lot!
Best, 
Fredrik

**Comment by fredjoha** [comment]
Thanks! Fixed
