### ISSUE TITLE
A Question about the Noiseless True Effect

### ISSUE THREAD

**Issue by uqhwen2** [clinicalml/cfrnet#8]
Hi Fredrik,

Thanks for your interesting work. I'm recently reading your paper, but have one confuison in my mind that can not go away. The confusion is, in the experiment part, you use the IHDP data set with setting "A" to generate treatment response (which is a linear response surface as declared by Hill in her 2011  BART paper, NPCI package also follows this convention). 

As stated in your paper, "Following Hill (2011), we use the _noiseless_ outcome to compute the true effect". Presumably, for one individual, the difference between two _noiseless_ outcome: **mu1 - mu0** (mu1 and mu0 for treated and control respectively) should strictly be **4** isn't it? But when I check the data provided, the difference between these two across all the samples is not a constant 4. It seems like the mu1 and mu0 provided also with noise?

I provided snapshot for them as follows:
<img width="526" alt="Screen Shot 2022-05-15 at 2 13 57 am" src="https://user-images.githubusercontent.com/103487148/168440027-c7ec39e1-88cf-43ad-8318-d34dd2685498.png">

I understand that the treatment response Y1 and Y0 (with one of them being counterfactual for each individual) come with noise, thus, there difference not necessarily being 4. But why **mu1 - mu0** not strictly being 4?

Thanks for any reply!

**Comment by uqhwen2** [comment]
The snapshot provided is the test set data.

**Comment by fredjoha** [comment]
Hu mu1-mu0 is the noiseless conditional average treatment effect, not the noiseless average effect. The average over those values should be 4 before the data is split into train and test, as determined by the NPCI package.
